
seed_everything: 42
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: logs
      name: fire_scars
      log_graph: false
      default_hp_metric: true
      prefix: ''
      comment: ''
      max_queue: 10
      flush_secs: 60
      filename_suffix: ''
  callbacks:
    - class_path: lightning.pytorch.callbacks.RichProgressBar
      init_args:
        refresh_rate: 1
        leave: true
        theme:
          description: white
          progress_bar: '
          progress_bar_finished: '
          progress_bar_pulse: '
          batch_progress: white
          time: grey54
          processing_speed: grey70
          metrics: white
          metrics_text_delimiter: ' '
          metrics_format: .3f
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val/loss  
        min_delta: 0.001
        patience: 5
        verbose: true
        mode: min  
        strict: true
        check_finite: true
        log_rank_zero_only: false
  fast_dev_run: false
  max_epochs: 50
  max_steps: -1
  overfit_batches: 0.0
  check_val_every_n_epoch: 1
  log_every_n_steps: 25
  enable_checkpointing: true
  accumulate_grad_batches: 2
  inference_mode: true
  use_distributed_sampler: true
  detect_anomaly: true
  barebones: false
  sync_batchnorm: true
  reload_dataloaders_every_n_epochs: 1
  default_root_dir: ./

model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    model_args:
      decoder: FCNDecoder
      pretrained: true
      backbone: prithvi_vit_100
      decoder_channels: 32
      in_channels: 1
      bands:
        - BLUE
        - GREEN
        - RED
        - NIR_NARROW
        - SWIR_1
        - SWIR_2
      num_frames: 1
      num_classes: 2
      head_dropout: 0.3
      decoder_num_convs: 4
      head_channel_list:
        - 32
    model_factory: PrithviModelFactory
    loss: dice
    ignore_index: -1
    lr: 0.0003
    freeze_backbone: false
    freeze_decoder: false
    plot_on_val: 5
    tiled_inference_parameters:
      h_crop: 512
      h_stride: 256
      w_crop: 512
      w_stride: 256
      average_patches: true

data:
  class_path: terratorch.datamodules.GenericNonGeoSegmentationDataModule
  init_args:
    batch_size: 4
    num_workers: 4
    train_data_root: datasets/fire_scars_train_val/train
    val_data_root: datasets/fire_scars_train_val/validation
    test_data_root: datasets/fire_scars_train_val/validation
    img_grep: '*_merged.tif'
    label_grep: '*.mask.tif'
    means:
      - 0.033349706741586264
      - 0.05701185520536176
      - 0.05889748132001316
      - 0.2323245113436119
      - 0.1972854853760658
      - 0.11944914225186566
    stds:
      - 0.02269135568823774
      - 0.026807560223070237
      - 0.04004109844362779
      - 0.07791732423672691
      - 0.08708738838140137
      - 0.07241979477437814
    num_classes: 2
    train_label_data_root: datasets/fire_scars_train_val/train
    val_label_data_root: datasets/fire_scars_train_val/validation
    test_label_data_root: datasets/fire_scars_train_val/validation
    ignore_split_file_extensions: true
    allow_substring_split_file: true
    dataset_bands:
      - BLUE
      - GREEN
      - RED
      - NIR_NARROW
      - SWIR_1
      - SWIR_2
    output_bands:
      - BLUE
      - GREEN
      - RED
      - NIR_NARROW
      - SWIR_1
      - SWIR_2
    constant_scale: 1.0
    rgb_indices:
      - 2
      - 1
      - 0
    train_transform:
      - class_path: albumentations.RandomResizedCrop
        init_args:
          height: 512
          width: 512
          scale: [0.8, 1.0]
          p: 1.0
      - class_path: albumentations.HorizontalFlip
        init_args:
          p: 0.5
      - class_path: albumentations.RandomRotate90
        init_args:
          p: 0.5
      - class_path: albumentations.GaussianBlur
        init_args:
          p: 0.3
      - class_path: albumentations.pytorch.ToTensorV2
        init_args:
          always_apply: true
          p: 1.0
    expand_temporal_dimension: false
    reduce_zero_label: false
    no_data_replace: 0.0
    no_label_replace: -1
    drop_last: true

out_dtype: int16
deploy_config_file: true

ModelCheckpoint:
  filename: '{epoch}'
  monitor: val/loss  
  verbose: true
  save_top_k: 3
  mode: min  
  save_weights_only: false

StateDictModelCheckpoint:
  filename: '{epoch}_state_dict'
  monitor: val/loss  
  verbose: true
  save_top_k: 3
  mode: min  
  save_weights_only: true

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.0003
    betas:
      - 0.9
      - 0.999
    eps: 1.0e-08
    weight_decay: 0.01
    amsgrad: true

lr_scheduler:
  class_path: lightning.pytorch.cli.ReduceLROnPlateau
  init_args:
    monitor: val/loss  
    mode: min  
    factor: 0.2
    patience: 5
    threshold: 0.0001
    threshold_mode: rel
    cooldown: 2
    min_lr: 1.0e-6
    eps: 1.0e-08
    verbose: true
